#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : zip
Version  : 3.0
Release  : 23
URL      : https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz
Source0  : https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/zip30.tar.gz
Summary  : Compressor/archiver for creating and modifying zipfiles
Group    : Development/Tools
License  : BSD-3-Clause
Requires: zip-bin = %{version}-%{release}
Requires: zip-license = %{version}-%{release}
Requires: zip-man = %{version}-%{release}
BuildRequires : bzip2-dev
Patch1: cflags.patch
Patch2: format.patch
Patch3: manpages.patch

%description
This Theos port supports all the unusual features of Theos filesystem.
Under Theos filesystem files are typed. Types include :
- stream
- relative
- keyed
- indexed (ISAM)
- program (86 real mode, 16 bits protected mode, 32 bits protected mode)
- directory
- library (contains files of any other types librry and directory excepted).

%package bin
Summary: bin components for the zip package.
Group: Binaries
Requires: zip-license = %{version}-%{release}

%description bin
bin components for the zip package.


%package license
Summary: license components for the zip package.
Group: Default

%description license
license components for the zip package.


%package man
Summary: man components for the zip package.
Group: Default

%description man
man components for the zip package.


%prep
%setup -q -n zip30
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552835238
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
make  %{?_smp_mflags} CFLAGS="$CFLAGS" BIND="gcc $LDFLAGS" -f unix/Makefile generic_gcc


%install
export SOURCE_DATE_EPOCH=1552835238
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/zip
cp LICENSE %{buildroot}/usr/share/package-licenses/zip/LICENSE
%makeinstall -f unix/Makefile

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zip
/usr/bin/zipcloak
/usr/bin/zipnote
/usr/bin/zipsplit

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/zip/LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/zip.1
/usr/share/man/man1/zipcloak.1
/usr/share/man/man1/zipnote.1
/usr/share/man/man1/zipsplit.1
